/**
 * Users API
 * Users API for the RecruitBuddy project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
//import { FieldContentType } from './fieldContentType';

export interface Field { 
    fieldID?: string;
    fieldName?: string;
    fieldLabel?: string;
    fieldLabelFont?: string;
    fieldLabelFontSize?: string;
    fieldLabelFormatting?: string;
    fieldDescription?: string;
    fieldContentType?: Map<string, string>;
    fieldContentFont?: string;
    fieldContentFontSize?: string;
    fieldContentFormatting?: string;
    associatedCSS?: string;
}