/**
 * Users API
 * Users API for the RecruitBuddy project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Nationality { 
    nationalityID?: string;
    code?: string;
    description?: DescriptionEnum;
}
//export namespace Nationality {
    export type DescriptionEnum = 'IE' | 'UK' | 'US' | 'IN';
    export const DescriptionEnum = {
        IE: 'IE' as DescriptionEnum,
        UK: 'UK' as DescriptionEnum,
        US: 'US' as DescriptionEnum,
        IN: 'IN' as DescriptionEnum
    };
//}