/**
 * Users API
 * Users API for the RecruitBuddy project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export type TemplateType = 'Resume' | 'Cover Letter';

export const TemplateType = {
    Resume: 'Resume' as TemplateType,
    CoverLetter: 'Cover Letter' as TemplateType
};