/**
 * Users API
 * Users API for the RecruitBuddy project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { TemplateSectionField } from './templateSectionField';

export interface TemplateSection { 
    templateSectionID?: string;
    sectionindex?: number;
    sectionType?: SectionTypeEnum;
    defaultSectionName?: string;
    description?: string;
    sectionIconRef?: string;
    helpIconRef?: string;
    deleteIconRef?: string;
    hasChildren?: boolean;
    associatedCSS?: string;
    sectionBarColor?: string;
    templateSectionFields?: Array<TemplateSectionField>;
}
//export namespace TemplateSection {
    export type SectionTypeEnum = 'Header Section' | 'Non Header Section';
    export const SectionTypeEnum = {
        HeaderSection: 'Header Section' as SectionTypeEnum,
        NonHeaderSection: 'Non Header Section' as SectionTypeEnum
    };
//}