/**
 * Users API
 * Users API for the RecruitBuddy project
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface UserVideo { 
    videoID?: string;
    videoURL?: string;
    fileName?: string;
    createdBy?: string;
    mimeType?: string;
    dateTimeCreated?: string;
    lastDateTimeUpdated?: string;
}